/**
 * generated by Xtext 2.20.0
 */
package org.mde.spec.spec;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mde.spec.spec.LoopCommand#getTimes <em>Times</em>}</li>
 *   <li>{@link org.mde.spec.spec.LoopCommand#getCommand <em>Command</em>}</li>
 * </ul>
 *
 * @see org.mde.spec.spec.SpecPackage#getLoopCommand()
 * @model
 * @generated
 */
public interface LoopCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Times</em>' attribute.
   * @see #setTimes(int)
   * @see org.mde.spec.spec.SpecPackage#getLoopCommand_Times()
   * @model
   * @generated
   */
  int getTimes();

  /**
   * Sets the value of the '{@link org.mde.spec.spec.LoopCommand#getTimes <em>Times</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Times</em>' attribute.
   * @see #getTimes()
   * @generated
   */
  void setTimes(int value);

  /**
   * Returns the value of the '<em><b>Command</b></em>' containment reference list.
   * The list contents are of type {@link org.mde.spec.spec.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' containment reference list.
   * @see org.mde.spec.spec.SpecPackage#getLoopCommand_Command()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommand();

} // LoopCommand
