/**
 * generated by Xtext 2.20.0
 */
package org.mde.spec.spec;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.mde.spec.spec.SpecFactory
 * @model kind="package"
 * @generated
 */
public interface SpecPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "spec";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mde.org/spec/Spec";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "spec";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpecPackage eINSTANCE = org.mde.spec.spec.impl.SpecPackageImpl.init();

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.ModelImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.CommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__COMMENT = 0;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__CUSTOM = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.OpenCommandImpl <em>Open Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.OpenCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getOpenCommand()
   * @generated
   */
  int OPEN_COMMAND = 2;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_COMMAND__VAR = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Open Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.ClickCommandImpl <em>Click Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.ClickCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getClickCommand()
   * @generated
   */
  int CLICK_COMMAND = 3;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND__CMD = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND__SELECTOR = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Point</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND__POINT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Click Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.SelectCommandImpl <em>Select Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.SelectCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getSelectCommand()
   * @generated
   */
  int SELECT_COMMAND = 4;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMMAND__VALUE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.SelectorImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 5;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__VAR = 0;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__STR = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__TYPE = 2;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.StoreCommandImpl <em>Store Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.StoreCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getStoreCommand()
   * @generated
   */
  int STORE_COMMAND = 6;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND__NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND__VALUE = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Store Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.RememberCommandImpl <em>Remember Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.RememberCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getRememberCommand()
   * @generated
   */
  int REMEMBER_COMMAND = 7;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMEMBER_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMEMBER_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMEMBER_COMMAND__PROP = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMEMBER_COMMAND__VAR = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Remember Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMEMBER_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.PropertyCommandImpl <em>Property Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.PropertyCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getPropertyCommand()
   * @generated
   */
  int PROPERTY_COMMAND = 8;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__PROP = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cond</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__COND = COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__VAL = COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND__VAR = COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Property Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.TypeCommandImpl <em>Type Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.TypeCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getTypeCommand()
   * @generated
   */
  int TYPE_COMMAND = 9;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_COMMAND__STR = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_COMMAND__VAR = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Type Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.SleepCommandImpl <em>Sleep Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.SleepCommandImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getSleepCommand()
   * @generated
   */
  int SLEEP_COMMAND = 10;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP_COMMAND__COMMENT = COMMAND__COMMENT;

  /**
   * The feature id for the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP_COMMAND__CUSTOM = COMMAND__CUSTOM;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP_COMMAND__TIME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sleep Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.ElementInScreenImpl <em>Element In Screen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.ElementInScreenImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getElementInScreen()
   * @generated
   */
  int ELEMENT_IN_SCREEN = 11;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_IN_SCREEN__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Element In Screen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_IN_SCREEN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.impl.VariableImpl
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mde.spec.spec.ElementType <em>Element Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mde.spec.spec.ElementType
   * @see org.mde.spec.spec.impl.SpecPackageImpl#getElementType()
   * @generated
   */
  int ELEMENT_TYPE = 13;


  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.mde.spec.spec.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.mde.spec.spec.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.mde.spec.spec.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.mde.spec.spec.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.Command#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see org.mde.spec.spec.Command#getComment()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Comment();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.Command#getCustom <em>Custom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Custom</em>'.
   * @see org.mde.spec.spec.Command#getCustom()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Custom();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.OpenCommand <em>Open Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Command</em>'.
   * @see org.mde.spec.spec.OpenCommand
   * @generated
   */
  EClass getOpenCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.mde.spec.spec.OpenCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.mde.spec.spec.OpenCommand#getVar()
   * @see #getOpenCommand()
   * @generated
   */
  EReference getOpenCommand_Var();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.ClickCommand <em>Click Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Command</em>'.
   * @see org.mde.spec.spec.ClickCommand
   * @generated
   */
  EClass getClickCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.ClickCommand#getCmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cmd</em>'.
   * @see org.mde.spec.spec.ClickCommand#getCmd()
   * @see #getClickCommand()
   * @generated
   */
  EAttribute getClickCommand_Cmd();

  /**
   * Returns the meta object for the containment reference '{@link org.mde.spec.spec.ClickCommand#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.mde.spec.spec.ClickCommand#getSelector()
   * @see #getClickCommand()
   * @generated
   */
  EReference getClickCommand_Selector();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.ClickCommand#getPoint <em>Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Point</em>'.
   * @see org.mde.spec.spec.ClickCommand#getPoint()
   * @see #getClickCommand()
   * @generated
   */
  EAttribute getClickCommand_Point();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.SelectCommand <em>Select Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Command</em>'.
   * @see org.mde.spec.spec.SelectCommand
   * @generated
   */
  EClass getSelectCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.mde.spec.spec.SelectCommand#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.mde.spec.spec.SelectCommand#getValue()
   * @see #getSelectCommand()
   * @generated
   */
  EReference getSelectCommand_Value();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see org.mde.spec.spec.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the reference '{@link org.mde.spec.spec.Selector#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.mde.spec.spec.Selector#getVar()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Var();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.Selector#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.mde.spec.spec.Selector#getStr()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Str();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.Selector#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.mde.spec.spec.Selector#getType()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Type();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.StoreCommand <em>Store Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store Command</em>'.
   * @see org.mde.spec.spec.StoreCommand
   * @generated
   */
  EClass getStoreCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.StoreCommand#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mde.spec.spec.StoreCommand#getName()
   * @see #getStoreCommand()
   * @generated
   */
  EAttribute getStoreCommand_Name();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.StoreCommand#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.mde.spec.spec.StoreCommand#getValue()
   * @see #getStoreCommand()
   * @generated
   */
  EAttribute getStoreCommand_Value();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.RememberCommand <em>Remember Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remember Command</em>'.
   * @see org.mde.spec.spec.RememberCommand
   * @generated
   */
  EClass getRememberCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.RememberCommand#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prop</em>'.
   * @see org.mde.spec.spec.RememberCommand#getProp()
   * @see #getRememberCommand()
   * @generated
   */
  EAttribute getRememberCommand_Prop();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.RememberCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.mde.spec.spec.RememberCommand#getVar()
   * @see #getRememberCommand()
   * @generated
   */
  EAttribute getRememberCommand_Var();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.PropertyCommand <em>Property Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Command</em>'.
   * @see org.mde.spec.spec.PropertyCommand
   * @generated
   */
  EClass getPropertyCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.PropertyCommand#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prop</em>'.
   * @see org.mde.spec.spec.PropertyCommand#getProp()
   * @see #getPropertyCommand()
   * @generated
   */
  EAttribute getPropertyCommand_Prop();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.PropertyCommand#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cond</em>'.
   * @see org.mde.spec.spec.PropertyCommand#getCond()
   * @see #getPropertyCommand()
   * @generated
   */
  EAttribute getPropertyCommand_Cond();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.PropertyCommand#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.mde.spec.spec.PropertyCommand#getVal()
   * @see #getPropertyCommand()
   * @generated
   */
  EAttribute getPropertyCommand_Val();

  /**
   * Returns the meta object for the reference '{@link org.mde.spec.spec.PropertyCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.mde.spec.spec.PropertyCommand#getVar()
   * @see #getPropertyCommand()
   * @generated
   */
  EReference getPropertyCommand_Var();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.TypeCommand <em>Type Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Command</em>'.
   * @see org.mde.spec.spec.TypeCommand
   * @generated
   */
  EClass getTypeCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.TypeCommand#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.mde.spec.spec.TypeCommand#getStr()
   * @see #getTypeCommand()
   * @generated
   */
  EAttribute getTypeCommand_Str();

  /**
   * Returns the meta object for the reference '{@link org.mde.spec.spec.TypeCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.mde.spec.spec.TypeCommand#getVar()
   * @see #getTypeCommand()
   * @generated
   */
  EReference getTypeCommand_Var();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.SleepCommand <em>Sleep Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sleep Command</em>'.
   * @see org.mde.spec.spec.SleepCommand
   * @generated
   */
  EClass getSleepCommand();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.SleepCommand#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.mde.spec.spec.SleepCommand#getTime()
   * @see #getSleepCommand()
   * @generated
   */
  EAttribute getSleepCommand_Time();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.ElementInScreen <em>Element In Screen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element In Screen</em>'.
   * @see org.mde.spec.spec.ElementInScreen
   * @generated
   */
  EClass getElementInScreen();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.ElementInScreen#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.mde.spec.spec.ElementInScreen#getElement()
   * @see #getElementInScreen()
   * @generated
   */
  EAttribute getElementInScreen_Element();

  /**
   * Returns the meta object for class '{@link org.mde.spec.spec.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.mde.spec.spec.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.mde.spec.spec.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mde.spec.spec.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for enum '{@link org.mde.spec.spec.ElementType <em>Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Element Type</em>'.
   * @see org.mde.spec.spec.ElementType
   * @generated
   */
  EEnum getElementType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SpecFactory getSpecFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.ModelImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.CommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__COMMENT = eINSTANCE.getCommand_Comment();

    /**
     * The meta object literal for the '<em><b>Custom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__CUSTOM = eINSTANCE.getCommand_Custom();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.OpenCommandImpl <em>Open Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.OpenCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getOpenCommand()
     * @generated
     */
    EClass OPEN_COMMAND = eINSTANCE.getOpenCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPEN_COMMAND__VAR = eINSTANCE.getOpenCommand_Var();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.ClickCommandImpl <em>Click Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.ClickCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getClickCommand()
     * @generated
     */
    EClass CLICK_COMMAND = eINSTANCE.getClickCommand();

    /**
     * The meta object literal for the '<em><b>Cmd</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_COMMAND__CMD = eINSTANCE.getClickCommand_Cmd();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK_COMMAND__SELECTOR = eINSTANCE.getClickCommand_Selector();

    /**
     * The meta object literal for the '<em><b>Point</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_COMMAND__POINT = eINSTANCE.getClickCommand_Point();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.SelectCommandImpl <em>Select Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.SelectCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getSelectCommand()
     * @generated
     */
    EClass SELECT_COMMAND = eINSTANCE.getSelectCommand();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_COMMAND__VALUE = eINSTANCE.getSelectCommand_Value();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.SelectorImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__VAR = eINSTANCE.getSelector_Var();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__STR = eINSTANCE.getSelector_Str();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__TYPE = eINSTANCE.getSelector_Type();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.StoreCommandImpl <em>Store Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.StoreCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getStoreCommand()
     * @generated
     */
    EClass STORE_COMMAND = eINSTANCE.getStoreCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_COMMAND__NAME = eINSTANCE.getStoreCommand_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_COMMAND__VALUE = eINSTANCE.getStoreCommand_Value();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.RememberCommandImpl <em>Remember Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.RememberCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getRememberCommand()
     * @generated
     */
    EClass REMEMBER_COMMAND = eINSTANCE.getRememberCommand();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMEMBER_COMMAND__PROP = eINSTANCE.getRememberCommand_Prop();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMEMBER_COMMAND__VAR = eINSTANCE.getRememberCommand_Var();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.PropertyCommandImpl <em>Property Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.PropertyCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getPropertyCommand()
     * @generated
     */
    EClass PROPERTY_COMMAND = eINSTANCE.getPropertyCommand();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_COMMAND__PROP = eINSTANCE.getPropertyCommand_Prop();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_COMMAND__COND = eINSTANCE.getPropertyCommand_Cond();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY_COMMAND__VAL = eINSTANCE.getPropertyCommand_Val();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_COMMAND__VAR = eINSTANCE.getPropertyCommand_Var();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.TypeCommandImpl <em>Type Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.TypeCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getTypeCommand()
     * @generated
     */
    EClass TYPE_COMMAND = eINSTANCE.getTypeCommand();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_COMMAND__STR = eINSTANCE.getTypeCommand_Str();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_COMMAND__VAR = eINSTANCE.getTypeCommand_Var();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.SleepCommandImpl <em>Sleep Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.SleepCommandImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getSleepCommand()
     * @generated
     */
    EClass SLEEP_COMMAND = eINSTANCE.getSleepCommand();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLEEP_COMMAND__TIME = eINSTANCE.getSleepCommand_Time();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.ElementInScreenImpl <em>Element In Screen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.ElementInScreenImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getElementInScreen()
     * @generated
     */
    EClass ELEMENT_IN_SCREEN = eINSTANCE.getElementInScreen();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT_IN_SCREEN__ELEMENT = eINSTANCE.getElementInScreen_Element();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.impl.VariableImpl
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.mde.spec.spec.ElementType <em>Element Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mde.spec.spec.ElementType
     * @see org.mde.spec.spec.impl.SpecPackageImpl#getElementType()
     * @generated
     */
    EEnum ELEMENT_TYPE = eINSTANCE.getElementType();

  }

} //SpecPackage
