/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpecStandaloneSetup extends SpecStandaloneSetupGenerated {

	public static void doSetup() {
		new SpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
