/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.mde.spec.ui.internal.SpecActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpecActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpecActivator activator = SpecActivator.getInstance();
		return activator != null ? activator.getInjector(SpecActivator.ORG_MDE_SPEC_SPEC) : null;
	}

}
