/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.mde.spec.ui.internal.SpecActivator;

public class SpecUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpecActivator.getInstance().getInjector("org.mde.spec.Spec");
	}

}
