/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpecScopeProvider extends DelegatingScopeProvider {
}
