/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SpecGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Model");
		private final Assignment cCommandsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCommandsCommandParserRuleCall_0 = (RuleCall)cCommandsAssignment.eContents().get(0);
		
		//Model:
		//	commands+=Command*;
		@Override public ParserRule getRule() { return rule; }
		
		//commands+=Command*
		public Assignment getCommandsAssignment() { return cCommandsAssignment; }
		
		//Command
		public RuleCall getCommandsCommandParserRuleCall_0() { return cCommandsCommandParserRuleCall_0; }
	}
	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOpenCommandParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cClickCommandParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCommentCommandParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSelectCommandParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRememberCommandParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cPropertyCommandParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cTypeCommandParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSleepCommandParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cCustomCommandParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		
		//Command:
		//	OpenCommand
		//	| ClickCommand
		//	| CommentCommand
		//	| SelectCommand
		//	| RememberCommand
		//	| PropertyCommand
		//	| TypeCommand
		//	| SleepCommand
		//	| CustomCommand;
		@Override public ParserRule getRule() { return rule; }
		
		//OpenCommand | ClickCommand | CommentCommand | SelectCommand | RememberCommand | PropertyCommand | TypeCommand |
		//SleepCommand | CustomCommand
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OpenCommand
		public RuleCall getOpenCommandParserRuleCall_0() { return cOpenCommandParserRuleCall_0; }
		
		//ClickCommand
		public RuleCall getClickCommandParserRuleCall_1() { return cClickCommandParserRuleCall_1; }
		
		//CommentCommand
		public RuleCall getCommentCommandParserRuleCall_2() { return cCommentCommandParserRuleCall_2; }
		
		//SelectCommand
		public RuleCall getSelectCommandParserRuleCall_3() { return cSelectCommandParserRuleCall_3; }
		
		//RememberCommand
		public RuleCall getRememberCommandParserRuleCall_4() { return cRememberCommandParserRuleCall_4; }
		
		//PropertyCommand
		public RuleCall getPropertyCommandParserRuleCall_5() { return cPropertyCommandParserRuleCall_5; }
		
		//TypeCommand
		public RuleCall getTypeCommandParserRuleCall_6() { return cTypeCommandParserRuleCall_6; }
		
		//SleepCommand
		public RuleCall getSleepCommandParserRuleCall_7() { return cSleepCommandParserRuleCall_7; }
		
		//CustomCommand
		public RuleCall getCustomCommandParserRuleCall_8() { return cCustomCommandParserRuleCall_8; }
	}
	public class OpenCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.OpenCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpenKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueValueParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//OpenCommand:
		//	"Open" value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//"Open" value=Value
		public Group getGroup() { return cGroup; }
		
		//"Open"
		public Keyword getOpenKeyword_0() { return cOpenKeyword_0; }
		
		//value=Value
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_1_0() { return cValueValueParserRuleCall_1_0; }
	}
	public class ClickCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.ClickCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cCmdAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cCmdClickKeyword_0_0 = (Keyword)cCmdAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cClickKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cOnKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cSelectorAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cSelectorSelectorParserRuleCall_1_2_0 = (RuleCall)cSelectorAssignment_1_2.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cClickKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cAtKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cPointAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cPointPointParserRuleCall_2_2_0 = (RuleCall)cPointAssignment_2_2.eContents().get(0);
		
		//ClickCommand:
		//	cmd="Click"
		//	| "Click" "on" selector=Selector
		//	| "Click" "at" point=Point;
		@Override public ParserRule getRule() { return rule; }
		
		//cmd="Click" | "Click" "on" selector=Selector | "Click" "at" point=Point
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//cmd="Click"
		public Assignment getCmdAssignment_0() { return cCmdAssignment_0; }
		
		//"Click"
		public Keyword getCmdClickKeyword_0_0() { return cCmdClickKeyword_0_0; }
		
		//"Click" "on" selector=Selector
		public Group getGroup_1() { return cGroup_1; }
		
		//"Click"
		public Keyword getClickKeyword_1_0() { return cClickKeyword_1_0; }
		
		//"on"
		public Keyword getOnKeyword_1_1() { return cOnKeyword_1_1; }
		
		//selector=Selector
		public Assignment getSelectorAssignment_1_2() { return cSelectorAssignment_1_2; }
		
		//Selector
		public RuleCall getSelectorSelectorParserRuleCall_1_2_0() { return cSelectorSelectorParserRuleCall_1_2_0; }
		
		//"Click" "at" point=Point
		public Group getGroup_2() { return cGroup_2; }
		
		//"Click"
		public Keyword getClickKeyword_2_0() { return cClickKeyword_2_0; }
		
		//"at"
		public Keyword getAtKeyword_2_1() { return cAtKeyword_2_1; }
		
		//point=Point
		public Assignment getPointAssignment_2_2() { return cPointAssignment_2_2; }
		
		//Point
		public RuleCall getPointPointParserRuleCall_2_2_0() { return cPointPointParserRuleCall_2_2_0; }
	}
	public class CommentCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.CommentCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStrAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStrSTRINGTerminalRuleCall_1_0 = (RuleCall)cStrAssignment_1.eContents().get(0);
		
		//CommentCommand:
		//	"#" str=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"#" str=STRING
		public Group getGroup() { return cGroup; }
		
		//"#"
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }
		
		//str=STRING
		public Assignment getStrAssignment_1() { return cStrAssignment_1; }
		
		//STRING
		public RuleCall getStrSTRINGTerminalRuleCall_1_0() { return cStrSTRINGTerminalRuleCall_1_0; }
	}
	public class SelectCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.SelectCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cWithinKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueSelectorParserRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cSelectKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueSelectorParserRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cSelectKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cVisibleKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cValueAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cValueSelectorParserRuleCall_2_2_0 = (RuleCall)cValueAssignment_2_2.eContents().get(0);
		
		//SelectCommand:
		//	"Within" value=Selector
		//	| "Select" value=Selector
		//	| "Select" "visible" value=Selector;
		@Override public ParserRule getRule() { return rule; }
		
		//"Within" value=Selector | "Select" value=Selector | "Select" "visible" value=Selector
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"Within" value=Selector
		public Group getGroup_0() { return cGroup_0; }
		
		//"Within"
		public Keyword getWithinKeyword_0_0() { return cWithinKeyword_0_0; }
		
		//value=Selector
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//Selector
		public RuleCall getValueSelectorParserRuleCall_0_1_0() { return cValueSelectorParserRuleCall_0_1_0; }
		
		//"Select" value=Selector
		public Group getGroup_1() { return cGroup_1; }
		
		//"Select"
		public Keyword getSelectKeyword_1_0() { return cSelectKeyword_1_0; }
		
		//value=Selector
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//Selector
		public RuleCall getValueSelectorParserRuleCall_1_1_0() { return cValueSelectorParserRuleCall_1_1_0; }
		
		//"Select" "visible" value=Selector
		public Group getGroup_2() { return cGroup_2; }
		
		//"Select"
		public Keyword getSelectKeyword_2_0() { return cSelectKeyword_2_0; }
		
		//"visible"
		public Keyword getVisibleKeyword_2_1() { return cVisibleKeyword_2_1; }
		
		//value=Selector
		public Assignment getValueAssignment_2_2() { return cValueAssignment_2_2; }
		
		//Selector
		public RuleCall getValueSelectorParserRuleCall_2_2_0() { return cValueSelectorParserRuleCall_2_2_0; }
	}
	public class RememberCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.RememberCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRememberKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPropAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropPropertyParserRuleCall_1_0 = (RuleCall)cPropAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVarVariableParserRuleCall_3_0 = (RuleCall)cVarAssignment_3.eContents().get(0);
		
		//RememberCommand:
		//	"Remember" prop=Property "as" var=Variable;
		@Override public ParserRule getRule() { return rule; }
		
		//"Remember" prop=Property "as" var=Variable
		public Group getGroup() { return cGroup; }
		
		//"Remember"
		public Keyword getRememberKeyword_0() { return cRememberKeyword_0; }
		
		//prop=Property
		public Assignment getPropAssignment_1() { return cPropAssignment_1; }
		
		//Property
		public RuleCall getPropPropertyParserRuleCall_1_0() { return cPropPropertyParserRuleCall_1_0; }
		
		//"as"
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }
		
		//var=Variable
		public Assignment getVarAssignment_3() { return cVarAssignment_3; }
		
		//Variable
		public RuleCall getVarVariableParserRuleCall_3_0() { return cVarVariableParserRuleCall_3_0; }
	}
	public class PropertyCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.PropertyCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPropAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropPropertyParserRuleCall_1_0 = (RuleCall)cPropAssignment_1.eContents().get(0);
		private final Assignment cCondAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCondConditionParserRuleCall_2_0 = (RuleCall)cCondAssignment_2.eContents().get(0);
		private final Assignment cValAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValValueParserRuleCall_3_0 = (RuleCall)cValAssignment_3.eContents().get(0);
		
		//PropertyCommand:
		//	"Property" prop=Property cond=Condition val=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//"Property" prop=Property cond=Condition val=Value
		public Group getGroup() { return cGroup; }
		
		//"Property"
		public Keyword getPropertyKeyword_0() { return cPropertyKeyword_0; }
		
		//prop=Property
		public Assignment getPropAssignment_1() { return cPropAssignment_1; }
		
		//Property
		public RuleCall getPropPropertyParserRuleCall_1_0() { return cPropPropertyParserRuleCall_1_0; }
		
		//cond=Condition
		public Assignment getCondAssignment_2() { return cCondAssignment_2; }
		
		//Condition
		public RuleCall getCondConditionParserRuleCall_2_0() { return cCondConditionParserRuleCall_2_0; }
		
		//val=Value
		public Assignment getValAssignment_3() { return cValAssignment_3; }
		
		//Value
		public RuleCall getValValueParserRuleCall_3_0() { return cValValueParserRuleCall_3_0; }
	}
	public class TypeCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.TypeCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValValueParserRuleCall_1_0 = (RuleCall)cValAssignment_1.eContents().get(0);
		
		//TypeCommand:
		//	"Type" val=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//"Type" val=Value
		public Group getGroup() { return cGroup; }
		
		//"Type"
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }
		
		//val=Value
		public Assignment getValAssignment_1() { return cValAssignment_1; }
		
		//Value
		public RuleCall getValValueParserRuleCall_1_0() { return cValValueParserRuleCall_1_0; }
	}
	public class SleepCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.SleepCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSleepKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cForKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTimeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTimeINTTerminalRuleCall_2_0 = (RuleCall)cTimeAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cSecondKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cSecondsKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		
		//SleepCommand:
		//	"Sleep" "for" time=INT ("second" | "seconds");
		@Override public ParserRule getRule() { return rule; }
		
		//"Sleep" "for" time=INT ("second" | "seconds")
		public Group getGroup() { return cGroup; }
		
		//"Sleep"
		public Keyword getSleepKeyword_0() { return cSleepKeyword_0; }
		
		//"for"
		public Keyword getForKeyword_1() { return cForKeyword_1; }
		
		//time=INT
		public Assignment getTimeAssignment_2() { return cTimeAssignment_2; }
		
		//INT
		public RuleCall getTimeINTTerminalRuleCall_2_0() { return cTimeINTTerminalRuleCall_2_0; }
		
		//("second" | "seconds")
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//"second"
		public Keyword getSecondKeyword_3_0() { return cSecondKeyword_3_0; }
		
		//"seconds"
		public Keyword getSecondsKeyword_3_1() { return cSecondsKeyword_3_1; }
	}
	public class CustomCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.CustomCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExclamationMarkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCommandAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCommandSTRINGTerminalRuleCall_1_0 = (RuleCall)cCommandAssignment_1.eContents().get(0);
		
		//CustomCommand:
		//	"!" command=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"!" command=STRING
		public Group getGroup() { return cGroup; }
		
		//"!"
		public Keyword getExclamationMarkKeyword_0() { return cExclamationMarkKeyword_0; }
		
		//command=STRING
		public Assignment getCommandAssignment_1() { return cCommandAssignment_1; }
		
		//STRING
		public RuleCall getCommandSTRINGTerminalRuleCall_1_0() { return cCommandSTRINGTerminalRuleCall_1_0; }
	}
	public class SelectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Selector");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValSTRINGTerminalRuleCall_0_0 = (RuleCall)cValAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cTypeAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cTypeElementTypeEnumRuleCall_1_0_0 = (RuleCall)cTypeAssignment_1_0.eContents().get(0);
		private final Assignment cValAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cValAssignment_1_1.eContents().get(0);
		private final Assignment cVarAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cVarVariableParserRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cTypeAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cTypeElementTypeEnumRuleCall_3_0_0 = (RuleCall)cTypeAssignment_3_0.eContents().get(0);
		private final Assignment cVarAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cVarVariableParserRuleCall_3_1_0 = (RuleCall)cVarAssignment_3_1.eContents().get(0);
		
		//Selector:
		//	val=STRING
		//	| type=ElementType val=STRING
		//	| var=Variable
		//	| type=ElementType var=Variable;
		@Override public ParserRule getRule() { return rule; }
		
		//val=STRING | type=ElementType val=STRING | var=Variable | type=ElementType var=Variable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//val=STRING
		public Assignment getValAssignment_0() { return cValAssignment_0; }
		
		//STRING
		public RuleCall getValSTRINGTerminalRuleCall_0_0() { return cValSTRINGTerminalRuleCall_0_0; }
		
		//type=ElementType val=STRING
		public Group getGroup_1() { return cGroup_1; }
		
		//type=ElementType
		public Assignment getTypeAssignment_1_0() { return cTypeAssignment_1_0; }
		
		//ElementType
		public RuleCall getTypeElementTypeEnumRuleCall_1_0_0() { return cTypeElementTypeEnumRuleCall_1_0_0; }
		
		//val=STRING
		public Assignment getValAssignment_1_1() { return cValAssignment_1_1; }
		
		//STRING
		public RuleCall getValSTRINGTerminalRuleCall_1_1_0() { return cValSTRINGTerminalRuleCall_1_1_0; }
		
		//var=Variable
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }
		
		//Variable
		public RuleCall getVarVariableParserRuleCall_2_0() { return cVarVariableParserRuleCall_2_0; }
		
		//type=ElementType var=Variable
		public Group getGroup_3() { return cGroup_3; }
		
		//type=ElementType
		public Assignment getTypeAssignment_3_0() { return cTypeAssignment_3_0; }
		
		//ElementType
		public RuleCall getTypeElementTypeEnumRuleCall_3_0_0() { return cTypeElementTypeEnumRuleCall_3_0_0; }
		
		//var=Variable
		public Assignment getVarAssignment_3_1() { return cVarAssignment_3_1; }
		
		//Variable
		public RuleCall getVarVariableParserRuleCall_3_1_0() { return cVarVariableParserRuleCall_3_1_0; }
	}
	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Property");
		private final RuleCall cPropertyTypeParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Property:
		//	PropertyType;
		@Override public ParserRule getRule() { return rule; }
		
		//PropertyType
		public RuleCall getPropertyTypeParserRuleCall() { return cPropertyTypeParserRuleCall; }
	}
	public class PropertyTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.PropertyType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//PropertyType:
		//	"text"
		//	| "class"
		//	| "value";
		@Override public ParserRule getRule() { return rule; }
		
		//"text" | "class" | "value"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"text"
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//"class"
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//"value"
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValVariableParserRuleCall_0_0 = (RuleCall)cValAssignment_0.eContents().get(0);
		private final Assignment cStrAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStrSTRINGTerminalRuleCall_1_0 = (RuleCall)cStrAssignment_1.eContents().get(0);
		
		//Value:
		//	val=Variable
		//	| str=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//val=Variable | str=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//val=Variable
		public Assignment getValAssignment_0() { return cValAssignment_0; }
		
		//Variable
		public RuleCall getValVariableParserRuleCall_0_0() { return cValVariableParserRuleCall_0_0; }
		
		//str=STRING
		public Assignment getStrAssignment_1() { return cStrAssignment_1; }
		
		//STRING
		public RuleCall getStrSTRINGTerminalRuleCall_1_0() { return cStrSTRINGTerminalRuleCall_1_0; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Condition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cShouldKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cBeKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cShouldKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cNotKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Keyword cBeKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Condition:
		//	"should" "be"
		//	| "should" "not" "be";
		@Override public ParserRule getRule() { return rule; }
		
		//"should" "be" | "should" "not" "be"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"should" "be"
		public Group getGroup_0() { return cGroup_0; }
		
		//"should"
		public Keyword getShouldKeyword_0_0() { return cShouldKeyword_0_0; }
		
		//"be"
		public Keyword getBeKeyword_0_1() { return cBeKeyword_0_1; }
		
		//"should" "not" "be"
		public Group getGroup_1() { return cGroup_1; }
		
		//"should"
		public Keyword getShouldKeyword_1_0() { return cShouldKeyword_1_0; }
		
		//"not"
		public Keyword getNotKeyword_1_1() { return cNotKeyword_1_1; }
		
		//"be"
		public Keyword getBeKeyword_1_2() { return cBeKeyword_1_2; }
	}
	public class PointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Point");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Point:
		//	"{" INT "," INT "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{" INT "," INT "}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDollarSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Variable:
		//	"$" name=STRING // fix this
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"$" name=STRING
		public Group getGroup() { return cGroup; }
		
		//"$"
		public Keyword getDollarSignKeyword_0() { return cDollarSignKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	
	public class ElementTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.mde.spec.Spec.ElementType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cButtonEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cButtonButtonKeyword_0_0 = (Keyword)cButtonEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cElementEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cElementElementKeyword_1_0 = (Keyword)cElementEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLinkEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLinkLinkKeyword_2_0 = (Keyword)cLinkEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cInputEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cInputInputKeyword_3_0 = (Keyword)cInputEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTextareaEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTextareaTextareaKeyword_4_0 = (Keyword)cTextareaEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum ElementType:
		//	button | element | link | input | textarea;
		public EnumRule getRule() { return rule; }
		
		//button | element | link | input | textarea
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//button
		public EnumLiteralDeclaration getButtonEnumLiteralDeclaration_0() { return cButtonEnumLiteralDeclaration_0; }
		
		//"button"
		public Keyword getButtonButtonKeyword_0_0() { return cButtonButtonKeyword_0_0; }
		
		//element
		public EnumLiteralDeclaration getElementEnumLiteralDeclaration_1() { return cElementEnumLiteralDeclaration_1; }
		
		//"element"
		public Keyword getElementElementKeyword_1_0() { return cElementElementKeyword_1_0; }
		
		//link
		public EnumLiteralDeclaration getLinkEnumLiteralDeclaration_2() { return cLinkEnumLiteralDeclaration_2; }
		
		//"link"
		public Keyword getLinkLinkKeyword_2_0() { return cLinkLinkKeyword_2_0; }
		
		//input
		public EnumLiteralDeclaration getInputEnumLiteralDeclaration_3() { return cInputEnumLiteralDeclaration_3; }
		
		//"input"
		public Keyword getInputInputKeyword_3_0() { return cInputInputKeyword_3_0; }
		
		//textarea
		public EnumLiteralDeclaration getTextareaEnumLiteralDeclaration_4() { return cTextareaEnumLiteralDeclaration_4; }
		
		//"textarea"
		public Keyword getTextareaTextareaKeyword_4_0() { return cTextareaTextareaKeyword_4_0; }
	}
	
	private final ModelElements pModel;
	private final CommandElements pCommand;
	private final OpenCommandElements pOpenCommand;
	private final ClickCommandElements pClickCommand;
	private final CommentCommandElements pCommentCommand;
	private final SelectCommandElements pSelectCommand;
	private final RememberCommandElements pRememberCommand;
	private final PropertyCommandElements pPropertyCommand;
	private final TypeCommandElements pTypeCommand;
	private final SleepCommandElements pSleepCommand;
	private final CustomCommandElements pCustomCommand;
	private final ElementTypeElements eElementType;
	private final SelectorElements pSelector;
	private final PropertyElements pProperty;
	private final PropertyTypeElements pPropertyType;
	private final ValueElements pValue;
	private final ConditionElements pCondition;
	private final PointElements pPoint;
	private final VariableElements pVariable;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SpecGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pCommand = new CommandElements();
		this.pOpenCommand = new OpenCommandElements();
		this.pClickCommand = new ClickCommandElements();
		this.pCommentCommand = new CommentCommandElements();
		this.pSelectCommand = new SelectCommandElements();
		this.pRememberCommand = new RememberCommandElements();
		this.pPropertyCommand = new PropertyCommandElements();
		this.pTypeCommand = new TypeCommandElements();
		this.pSleepCommand = new SleepCommandElements();
		this.pCustomCommand = new CustomCommandElements();
		this.eElementType = new ElementTypeElements();
		this.pSelector = new SelectorElements();
		this.pProperty = new PropertyElements();
		this.pPropertyType = new PropertyTypeElements();
		this.pValue = new ValueElements();
		this.pCondition = new ConditionElements();
		this.pPoint = new PointElements();
		this.pVariable = new VariableElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.mde.spec.Spec".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	commands+=Command*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Command:
	//	OpenCommand
	//	| ClickCommand
	//	| CommentCommand
	//	| SelectCommand
	//	| RememberCommand
	//	| PropertyCommand
	//	| TypeCommand
	//	| SleepCommand
	//	| CustomCommand;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}
	
	//OpenCommand:
	//	"Open" value=Value;
	public OpenCommandElements getOpenCommandAccess() {
		return pOpenCommand;
	}
	
	public ParserRule getOpenCommandRule() {
		return getOpenCommandAccess().getRule();
	}
	
	//ClickCommand:
	//	cmd="Click"
	//	| "Click" "on" selector=Selector
	//	| "Click" "at" point=Point;
	public ClickCommandElements getClickCommandAccess() {
		return pClickCommand;
	}
	
	public ParserRule getClickCommandRule() {
		return getClickCommandAccess().getRule();
	}
	
	//CommentCommand:
	//	"#" str=STRING;
	public CommentCommandElements getCommentCommandAccess() {
		return pCommentCommand;
	}
	
	public ParserRule getCommentCommandRule() {
		return getCommentCommandAccess().getRule();
	}
	
	//SelectCommand:
	//	"Within" value=Selector
	//	| "Select" value=Selector
	//	| "Select" "visible" value=Selector;
	public SelectCommandElements getSelectCommandAccess() {
		return pSelectCommand;
	}
	
	public ParserRule getSelectCommandRule() {
		return getSelectCommandAccess().getRule();
	}
	
	//RememberCommand:
	//	"Remember" prop=Property "as" var=Variable;
	public RememberCommandElements getRememberCommandAccess() {
		return pRememberCommand;
	}
	
	public ParserRule getRememberCommandRule() {
		return getRememberCommandAccess().getRule();
	}
	
	//PropertyCommand:
	//	"Property" prop=Property cond=Condition val=Value;
	public PropertyCommandElements getPropertyCommandAccess() {
		return pPropertyCommand;
	}
	
	public ParserRule getPropertyCommandRule() {
		return getPropertyCommandAccess().getRule();
	}
	
	//TypeCommand:
	//	"Type" val=Value;
	public TypeCommandElements getTypeCommandAccess() {
		return pTypeCommand;
	}
	
	public ParserRule getTypeCommandRule() {
		return getTypeCommandAccess().getRule();
	}
	
	//SleepCommand:
	//	"Sleep" "for" time=INT ("second" | "seconds");
	public SleepCommandElements getSleepCommandAccess() {
		return pSleepCommand;
	}
	
	public ParserRule getSleepCommandRule() {
		return getSleepCommandAccess().getRule();
	}
	
	//CustomCommand:
	//	"!" command=STRING;
	public CustomCommandElements getCustomCommandAccess() {
		return pCustomCommand;
	}
	
	public ParserRule getCustomCommandRule() {
		return getCustomCommandAccess().getRule();
	}
	
	//enum ElementType:
	//	button | element | link | input | textarea;
	public ElementTypeElements getElementTypeAccess() {
		return eElementType;
	}
	
	public EnumRule getElementTypeRule() {
		return getElementTypeAccess().getRule();
	}
	
	//Selector:
	//	val=STRING
	//	| type=ElementType val=STRING
	//	| var=Variable
	//	| type=ElementType var=Variable;
	public SelectorElements getSelectorAccess() {
		return pSelector;
	}
	
	public ParserRule getSelectorRule() {
		return getSelectorAccess().getRule();
	}
	
	//Property:
	//	PropertyType;
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}
	
	//PropertyType:
	//	"text"
	//	| "class"
	//	| "value";
	public PropertyTypeElements getPropertyTypeAccess() {
		return pPropertyType;
	}
	
	public ParserRule getPropertyTypeRule() {
		return getPropertyTypeAccess().getRule();
	}
	
	//Value:
	//	val=Variable
	//	| str=STRING;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//Condition:
	//	"should" "be"
	//	| "should" "not" "be";
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Point:
	//	"{" INT "," INT "}";
	public PointElements getPointAccess() {
		return pPoint;
	}
	
	public ParserRule getPointRule() {
		return getPointAccess().getRule();
	}
	
	//Variable:
	//	"$" name=STRING // fix this
	//;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
