/*
 * generated by Xtext 2.20.0
 */
package org.mde.spec.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.mde.spec.SpecRuntimeModule
import org.mde.spec.SpecStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SpecIdeSetup extends SpecStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SpecRuntimeModule, new SpecIdeModule))
	}
	
}
